### ISSUE TITLE
Error in Training

### ISSUE THREAD

**Issue by wx1900** [XinnuoXu/mmi_anti_pytorch#1]
Traceback (most recent call last):
  File "translate.py", line 157, in <module>
    main()
  File "translate.py", line 119, in main
    batch_data = translator.translate_batch(batch, data)
  File "/home/thea/cikm/mmi_anti_pytorch/onmt/translate/Translator.py", line 205, in translate_batch
    ret = self._from_beam(beam)
  File "/home/thea/cikm/mmi_anti_pytorch/onmt/translate/Translator.py", line 234, in _from_beam
    best_scores, best_scores_id = self.tt.FloatTensor(b.ended_sentences_scores).topk(n_best, 0, True, True)
RuntimeError: invalid argument 3: dim not in range at /pytorch/aten/src/TH/generic/THTensorMath.c:3436

Hi XinnouXu, I caught an error in training 'python translate.py -model modelname' and really need some help here.
Thanks in advance!

**Comment by XinnuoXu** [comment]
@wx1900 Hi, Xu, sorry I'm a bit busy these days. I will come back to you in this week : )

**Comment by vnnw** [comment]
I am interested in this project, too. 
But currently the repo is buggy, hope it will be fixed soon.

**Comment by XinnuoXu** [comment]
@vnnw @wx1900 Hey guys, it's been fixed. Please give it a try : )
